2025-08-01 12:12:38,745 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:38,747 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:40,007 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:40,008 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:40,085 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:40,085 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:40,085 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:40,085 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:40,367 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:40,368 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:40,446 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:40,446 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:40,446 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:40,446 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:40,726 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:40,727 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:40,804 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:40,804 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:40,804 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:40,804 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:41,078 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:41,079 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:41,154 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:41,155 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:41,155 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:41,155 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:41,429 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:41,430 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:41,506 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:41,507 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:41,507 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:41,507 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:41,781 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:41,782 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:41,858 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:41,858 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:41,858 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:41,859 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:42,126 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:42,127 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:42,201 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:42,202 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:42,202 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:42,202 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:42,457 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:42,458 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:42,535 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:42,535 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:42,535 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:42,535 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:42,813 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:42,814 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:42,895 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:42,896 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:42,896 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:42,896 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:43,188 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:12:43,189 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:12:43,273 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:43,273 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:43,273 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:43,274 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:43,308 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:12:43,309 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:12:43,311 - ERROR - [app.py:262] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 237, in generate_synthetic_data
    return render_template('results.html',
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/templates/results.html", line 62, in top-level template code
    {% if value is list %}
jinja2.exceptions.TemplateRuntimeError: No test named 'list' found.

2025-08-01 12:12:43,312 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:12:43] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:12:43,316 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:12:43] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:13:17,258 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:13:17] "GET / HTTP/1.1" 200 -
2025-08-01 12:13:17,263 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:13:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:13:17,265 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:13:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:17:08,851 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:17:09,018 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:17:10,809 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:17:10,819 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:17:14,050 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:17:14] "POST /info HTTP/1.1" 200 -
2025-08-01 12:17:19,444 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:19,445 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:21,400 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:21,400 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:21,416 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:21,416 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:21,416 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:21,417 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:21,932 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:21,933 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:21,949 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:21,949 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:21,950 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:21,950 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:22,456 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:22,456 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:22,472 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:22,472 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:22,473 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:22,473 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:22,995 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:22,996 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:23,013 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:23,013 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:23,013 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:23,013 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:23,545 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:23,546 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:23,562 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:23,562 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:23,563 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:23,563 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:24,090 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:24,091 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:24,106 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:24,107 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:24,107 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:24,107 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:24,645 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:24,645 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:24,662 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:24,662 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:24,663 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:24,663 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:25,263 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:25,264 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:25,286 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:25,286 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:25,287 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:25,287 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:25,878 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:25,879 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:25,902 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:25,902 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:25,902 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:25,902 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:26,600 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:17:26,601 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:17:26,620 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:26,621 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:26,621 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:26,621 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:26,657 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:17:26,657 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:17:26,673 - ERROR - [app.py:288] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 255, in generate_synthetic_data
    pca_data = get_pca_data(real_df_processed, final_synthetic_df.pipe(prepare_data)[0])
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 167, in get_pca_data
    synth_scaled = scaler.transform(synthetic_df_processed)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/sklearn/preprocessing/_data.py", line 1062, in transform
    X = validate_data(
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py", line 2919, in validate_data
    _check_feature_names(_estimator, X, reset=reset)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py", line 2777, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names must be in the same order as they were in fit.


2025-08-01 12:17:26,677 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:17:26] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:17:26,687 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:17:26] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:18:33,446 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:18:33] "GET / HTTP/1.1" 200 -
2025-08-01 12:18:33,455 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:18:33] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:18:33,459 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:18:33] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:18:38,358 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:18:38] "POST /info HTTP/1.1" 200 -
2025-08-01 12:20:07,117 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:20:07,240 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:20:09,034 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:20:09,043 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:20:10,023 - ERROR - [app.py:306] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 215, in generate_synthetic_data
    real_df_processed, inversion_maps = prepare_data(real_df_raw)
ValueError: too many values to unpack (expected 2)

2025-08-01 12:20:10,030 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:10] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:20:10,047 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:10] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:20:11,510 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:11] "GET / HTTP/1.1" 200 -
2025-08-01 12:20:11,517 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:11] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:20:11,520 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:11] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:20:14,372 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:14] "POST /info HTTP/1.1" 200 -
2025-08-01 12:20:19,653 - ERROR - [app.py:306] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 215, in generate_synthetic_data
    real_df_processed, inversion_maps = prepare_data(real_df_raw)
ValueError: too many values to unpack (expected 2)

2025-08-01 12:20:19,654 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:19] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:20:19,662 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:20:21,218 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:21] "GET / HTTP/1.1" 200 -
2025-08-01 12:20:21,221 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:21] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:20:21,225 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:20:21] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:24:43,517 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:24:43,676 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:24:45,489 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:24:45,498 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:24:48,536 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:24:48] "POST /info HTTP/1.1" 200 -
2025-08-01 12:24:53,535 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:53,536 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:53,870 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:53,871 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:53,890 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:53,891 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:53,891 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:53,891 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:53,983 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:53,984 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:54,005 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,005 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,005 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,005 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,110 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:54,111 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:54,132 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,133 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,133 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,133 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,232 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:54,232 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:54,252 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,252 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,252 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,252 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,351 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:54,352 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:54,372 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,372 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,372 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,372 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,476 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:54,477 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:54,497 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,498 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,498 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,498 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,602 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:54,603 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:54,623 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,624 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,624 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,624 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,724 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:54,724 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:54,744 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,744 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,744 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,744 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,844 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:54,844 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:54,864 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,864 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,864 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,864 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,963 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:24:54,964 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:24:54,984 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,984 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:54,984 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:54,984 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:55,016 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:24:55,016 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:24:55,031 - ERROR - [app.py:296] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 271, in generate_synthetic_data
    return render_template('results.html',
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/templates/results.html", line 62, in top-level template code
    {% if value is list %}
jinja2.exceptions.TemplateRuntimeError: No test named 'list' found.

2025-08-01 12:24:55,032 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:24:55] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:24:55,043 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:24:55] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:24:56,685 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:24:56] "GET / HTTP/1.1" 200 -
2025-08-01 12:24:56,690 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:24:56] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:24:56,693 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:24:56] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:26:57,317 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:26:57,630 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:26:59,387 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:26:59,396 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:27:01,803 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:27:01] "POST /info HTTP/1.1" 200 -
2025-08-01 12:27:02,663 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:02,663 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:02,959 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:02,960 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:03,364 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:03,364 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:03,461 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:03,461 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:03,549 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:03,550 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:03,637 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:03,638 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:03,727 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:03,727 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:03,816 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:03,816 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:03,903 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:03,903 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:03,991 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:03,992 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:04,083 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:04,084 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:04,116 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:04,116 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:04,131 - ERROR - [app.py:296] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 271, in generate_synthetic_data
    return render_template('results.html',
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/templates/results.html", line 62, in top-level template code
    {% if value is list %}
jinja2.exceptions.TemplateRuntimeError: No test named 'list' found.

2025-08-01 12:27:04,132 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:27:04] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:27:04,145 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:27:04] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:27:05,178 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:27:05] "GET / HTTP/1.1" 200 -
2025-08-01 12:27:05,180 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:27:05] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:27:05,182 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:27:05] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:27:10,080 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:27:10] "POST /info HTTP/1.1" 200 -
2025-08-01 12:27:14,279 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:14,280 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:15,453 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:15,454 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:15,520 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:15,520 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:15,520 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:15,521 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:15,793 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:15,794 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:15,859 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:15,860 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:15,860 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:15,860 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:16,158 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:16,159 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:16,224 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:16,225 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:16,225 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:16,225 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:16,499 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:16,500 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:16,567 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:16,568 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:16,568 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:16,568 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:16,841 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:16,842 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:16,909 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:16,909 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:16,909 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:16,910 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:17,183 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:17,183 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:17,251 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:17,251 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:17,251 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:17,251 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:17,530 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:17,531 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:17,598 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:17,598 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:17,598 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:17,598 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:17,871 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:17,872 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:17,939 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:17,940 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:17,940 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:17,940 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:18,213 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:18,214 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:18,281 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:18,281 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:18,281 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:18,281 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:18,557 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:27:18,558 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:27:18,626 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:18,627 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:18,627 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:18,627 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:18,658 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:27:18,659 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:27:18,661 - ERROR - [app.py:296] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 271, in generate_synthetic_data
    return render_template('results.html',
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/templates/results.html", line 62, in top-level template code
    {% if value is list %}
jinja2.exceptions.TemplateRuntimeError: No test named 'list' found.

2025-08-01 12:27:18,661 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:27:18] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:27:18,671 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:27:18] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:29:07,733 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:29:07,859 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:29:09,991 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:29:10,010 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:29:12,533 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:12,534 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:13,723 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:13,724 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:13,792 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:13,792 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:13,792 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:13,793 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:14,098 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:14,099 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:14,169 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:14,170 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:14,170 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:14,170 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:14,456 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:14,457 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:14,526 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:14,526 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:14,526 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:14,526 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:14,809 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:14,810 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:14,879 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:14,879 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:14,879 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:14,879 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:15,159 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:15,160 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:15,236 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:15,237 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:15,237 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:15,237 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:15,525 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:15,526 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:15,596 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:15,596 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:15,596 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:15,597 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:15,879 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:15,880 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:15,948 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:15,948 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:15,948 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:15,948 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:16,262 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:16,263 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:16,333 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:16,333 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:16,334 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:16,334 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:16,639 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:16,641 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:16,710 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:16,710 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:16,710 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:16,710 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:16,987 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:29:16,988 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:29:17,055 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:17,055 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:17,055 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:17,056 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:17,088 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:29:17,089 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:29:17,102 - ERROR - [app.py:293] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 268, in generate_synthetic_data
    return render_template('results.html',
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/templates/results.html", line 62, in top-level template code
    {% if value is list %}
jinja2.exceptions.TemplateRuntimeError: No test named 'list' found.

2025-08-01 12:29:17,103 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:29:17] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:29:17,116 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:29:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:31:39,211 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:31:39,367 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:31:41,139 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:31:41,149 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:31:48,111 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:48,112 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:49,341 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:49,342 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:49,411 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:49,411 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:49,411 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:49,411 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:49,698 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:49,699 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:49,768 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:49,768 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:49,768 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:49,768 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:50,052 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:50,053 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:50,121 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:50,122 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:50,122 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:50,122 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:50,402 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:50,403 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:50,471 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:50,471 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:50,471 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:50,471 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:50,750 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:50,751 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:50,820 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:50,820 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:50,820 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:50,820 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:51,106 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:51,107 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:51,175 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:51,176 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:51,176 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:51,176 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:51,456 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:51,457 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:51,525 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:51,525 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:51,525 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:51,525 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:51,832 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:51,833 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:51,901 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:51,901 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:51,901 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:51,901 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:52,181 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:52,182 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:52,250 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:52,251 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:52,251 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:52,251 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:52,518 - INFO - [app.py:61] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:31:52,519 - INFO - [app.py:69] - Post-processing complete.
2025-08-01 12:31:52,586 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:52,586 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:52,586 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:52,587 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:52,620 - INFO - [app.py:45] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:31:52,620 - INFO - [app.py:56] - Data preparation complete.
2025-08-01 12:31:52,634 - ERROR - [app.py:296] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 271, in generate_synthetic_data
    return render_template('results.html',
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/templates/results.html", line 62, in top-level template code
    {% if value is list %}
jinja2.exceptions.TemplateRuntimeError: No test named 'list' found.

2025-08-01 12:31:52,635 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:31:52] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:31:52,650 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:31:52] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:36:13,473 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:36:13] "GET / HTTP/1.1" 200 -
2025-08-01 12:36:13,479 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:36:13] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:36:13,483 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:36:13] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:41:20,582 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:41:20,746 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:41:22,607 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:41:22,621 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:42:38,264 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:42:38,396 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:42:40,205 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:42:40,214 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:42:42,430 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:42:42] "POST /info HTTP/1.1" 200 -
2025-08-01 12:42:45,627 - ERROR - [app.py:299] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 208, in generate_synthetic_data
    real_df_processed, inversion_maps = prepare_data(real_df_raw)
ValueError: too many values to unpack (expected 2)

2025-08-01 12:42:45,634 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:42:45] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:42:45,642 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:42:45] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:43:32,193 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:43:32] "GET / HTTP/1.1" 200 -
2025-08-01 12:43:32,197 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:43:32] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:43:32,199 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:43:32] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:43:35,097 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:43:35] "POST /info HTTP/1.1" 200 -
2025-08-01 12:43:38,653 - ERROR - [app.py:299] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 208, in generate_synthetic_data
    real_df_processed, inversion_maps = prepare_data(real_df_raw)
ValueError: too many values to unpack (expected 2)

2025-08-01 12:43:38,654 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:43:38] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:43:38,659 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:43:38] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:43:40,113 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:43:40] "GET / HTTP/1.1" 200 -
2025-08-01 12:43:40,119 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:43:40] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:43:40,122 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:43:40] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:46:28,654 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:46:28] "POST /info HTTP/1.1" 200 -
2025-08-01 12:46:34,162 - ERROR - [app.py:299] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 208, in generate_synthetic_data
    real_df_processed, inversion_maps = prepare_data(real_df_raw)
ValueError: too many values to unpack (expected 2)

2025-08-01 12:46:34,163 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:46:34] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:46:34,171 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:46:34] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:49:29,639 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:49:29,833 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:49:31,686 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:49:31,697 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:50:27,109 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:50:27] "GET / HTTP/1.1" 200 -
2025-08-01 12:50:27,116 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:50:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:50:27,121 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:50:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:50:30,354 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:50:30] "POST /info HTTP/1.1" 200 -
2025-08-01 12:50:34,608 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:34,608 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,024 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:35,025 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:35,065 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,065 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,065 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,065 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,163 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:35,163 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:35,200 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,200 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,200 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,200 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,302 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:35,303 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:35,341 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,341 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,341 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,341 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,439 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:35,440 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:35,477 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,478 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,478 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,478 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,585 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:35,586 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:35,626 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,627 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,627 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,627 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,737 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:35,738 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:35,779 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,780 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,780 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,780 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,892 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:35,892 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:35,934 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,934 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:35,934 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:35,934 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:36,044 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:36,045 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:36,087 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:36,087 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:36,087 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:36,087 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:36,197 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:36,198 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:36,237 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:36,237 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:36,237 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:36,237 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:36,345 - INFO - [app.py:66] - Pipeline Stage 3: Post-processing Data...
2025-08-01 12:50:36,345 - INFO - [app.py:74] - Post-processing complete.
2025-08-01 12:50:36,384 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:36,384 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:36,384 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:36,384 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:36,416 - INFO - [app.py:50] - Pipeline Stage 1: Preparing Data...
2025-08-01 12:50:36,416 - INFO - [app.py:61] - Data preparation complete.
2025-08-01 12:50:36,429 - ERROR - [app.py:300] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 275, in generate_synthetic_data
    return render_template('results.html',
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/templates/results.html", line 62, in top-level template code
    {% if value is list %}
jinja2.exceptions.TemplateRuntimeError: No test named 'list' found.

2025-08-01 12:50:36,430 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:50:36] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:50:36,440 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:50:36] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:54:02,643 - INFO - [_internal.py:97] -  * Detected change in '/Users/jayanthsivakumar/Desktop/kNNMTD/app.py', reloading
2025-08-01 12:54:02,765 - INFO - [_internal.py:97] -  * Restarting with stat
2025-08-01 12:54:04,308 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 12:54:04,317 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 12:54:59,779 - ERROR - [app.py:297] - An unexpected error occurred: Traceback (most recent call last):
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/app.py", line 272, in generate_synthetic_data
    return render_template('results.html',
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/jayanthsivakumar/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jayanthsivakumar/Desktop/kNNMTD/templates/results.html", line 62, in top-level template code
    {% if value is list %}
jinja2.exceptions.TemplateRuntimeError: No test named 'list' found.

2025-08-01 12:54:59,781 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:54:59] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:54:59,793 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:54:59] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:57:50,712 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:57:50] "GET / HTTP/1.1" 200 -
2025-08-01 12:57:50,716 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:57:50] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:57:50,720 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:57:50] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 12:59:38,255 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:59:38] "POST /info HTTP/1.1" 200 -
2025-08-01 12:59:55,472 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:59:55] "POST /generate HTTP/1.1" 200 -
2025-08-01 12:59:55,481 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 12:59:55] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-08-01 13:28:06,843 - WARNING - [_internal.py:97] -  * Debugger is active!
2025-08-01 13:28:06,852 - INFO - [_internal.py:97] -  * Debugger PIN: 142-116-905
2025-08-01 13:34:30,033 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 13:34:30] "GET / HTTP/1.1" 200 -
2025-08-01 13:34:30,050 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 13:34:30] "GET /static/css/style.css HTTP/1.1" 200 -
2025-08-01 13:34:30,050 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 13:34:30] "GET /static/css/style.css HTTP/1.1" 200 -
2025-08-01 13:34:52,517 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 13:34:52] "POST /info HTTP/1.1" 200 -
2025-08-01 13:35:17,138 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 13:35:17] "POST /generate HTTP/1.1" 200 -
2025-08-01 13:35:17,152 - INFO - [_internal.py:97] - 127.0.0.1 - - [01/Aug/2025 13:35:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
